version: "3.8"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend_nginx.conf:/etc/nginx/conf.d/frontend_nginx.conf
      - ./backend_nginx.conf:/etc/nginx/conf.d/backend_nginx.conf
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    command: /bin/sh -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - db
      - frontend
  
  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
      - webroot:/var/www/certbot
    entrypoint:
      "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait
      $${!}; done;'"

  # Define the database service
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nsl
      POSTGRES_USER: nsl
      POSTGRES_PASSWORD: Ri0+WBk.@4vx@r£ZZj3o<s\Mpw£
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nsl -d nsl"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Define the Django backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env

  # Define the React frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production

volumes:
  postgres_data:
  certs:
  webroot: