version: "3.8"

services:
  # Define the database service
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nsl
      POSTGRES_USER: nsl
      POSTGRES_PASSWORD: Ri0+WBk.@4vx@r£ZZj3o<s\Mpw£
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nsl -d nsl"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  # Define the Django backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env

  # Define the React frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.production

volumes:
  postgres_data:
