# Generated by Django 4.2 on 2023-09-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.PositiveIntegerField()),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('coach_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stadium', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('manager_image', models.ImageField(blank=True, null=True, upload_to='manager_images/')),
                ('coach_image', models.ImageField(blank=True, null=True, upload_to='coach_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('fastest_goal_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='khelxa.club')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='khelxa.club')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goals_scored', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='player_images/')),
                ('position', models.CharField(choices=[('Mid Fielder', 'mid_fielder'), ('Forward', 'farward'), ('Goal Kepper', 'goal_kepper'), ('Defender', 'defender')], max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.club')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('sub_tittle', models.CharField(max_length=100)),
                ('video_url', models.URLField(max_length=60)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.season')),
            ],
        ),
        migrations.CreateModel(
            name='TopScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.season')),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('red_cards', models.PositiveIntegerField(default=0)),
                ('yellow_cards', models.PositiveIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.season')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponser_name', models.CharField(max_length=100)),
                ('sponser_image', models.ImageField(upload_to='sponser_image/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.season')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_goals', models.PositiveIntegerField()),
                ('away_team_goals', models.PositiveIntegerField()),
                ('red_cards_home_team', models.PositiveIntegerField(default=0)),
                ('red_cards_away_team', models.PositiveIntegerField(default=0)),
                ('yellow_cards_home_team', models.PositiveIntegerField(default=0)),
                ('yellow_cards_away_team', models.PositiveIntegerField(default=0)),
                ('fastest_goal_minute', models.PositiveIntegerField(blank=True, null=True)),
                ('fastest_goal_scorer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='khelxa.player')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.fixture')),
            ],
        ),
        migrations.CreateModel(
            name='NewsAndAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('news', 'NEWS'), ('announcement', 'ANNOUNCEMENT')], max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('images', models.ManyToManyField(blank=True, related_name='news_and_announcements', to='khelxa.images')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('sub_tittle', models.CharField(max_length=100)),
                ('images', models.ManyToManyField(to='khelxa.images')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khelxa.season')),
            ],
        ),
        migrations.AddField(
            model_name='fixture',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_fixtures', to='khelxa.season'),
        ),
        migrations.AddField(
            model_name='club',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='khelxa.season'),
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_coach', to='khelxa.club')),
                ('best_defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_defender', to='khelxa.player')),
                ('best_emerging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_emerging', to='khelxa.player')),
                ('best_forward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_forward', to='khelxa.player')),
                ('best_goalkepper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_goalkepper', to='khelxa.player')),
                ('best_midfielder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_midfielder', to='khelxa.player')),
                ('man_of_season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='man_of_season', to='khelxa.player')),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='khelxa.season')),
            ],
        ),
    ]
