# Generated by Django 4.2 on 2023-09-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandannouncement',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
