# Generated by Django 4.2 on 2023-09-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0002_alter_newsandannouncement_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='fastest_goal_minute',
        ),
    ]
