# Generated by Django 4.2 on 2023-09-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0003_remove_fixture_fastest_goal_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='goals_scored',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Mid Fielder', 'mid_fielder'), ('Forward', 'farward'), ('Goal Kepper', 'goal_kepper'), ('Defender', 'defender')], max_length=30),
        ),
        migrations.AlterField(
            model_name='player',
            name='red_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='yellow_cards',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
