# Generated by Django 4.2 on 2023-09-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0004_alter_player_goals_scored_alter_player_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='coach_image',
        ),
        migrations.RemoveField(
            model_name='club',
            name='coach_name',
        ),
        migrations.RemoveField(
            model_name='club',
            name='manager_image',
        ),
        migrations.RemoveField(
            model_name='club',
            name='manager_name',
        ),
    ]
