# Generated by Django 4.2 on 2023-09-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0005_remove_club_coach_image_remove_club_coach_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Mid Fielder', 'mid_fielder'), ('Forward', 'farward'), ('Goal Kepper', 'goal_kepper'), ('Defender', 'defender'), ('coach', 'COACH'), ('manager', 'MANAGER')], max_length=30),
        ),
    ]
