# Generated by Django 4.2 on 2023-09-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0006_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Mid Fielder', 'mid_fielder'), ('Forward', 'farward'), ('Goal Kepper', 'goal_kepper'), ('Defender', 'defender'), ('Coach', 'COACH'), ('Manager', 'MANAGER')], max_length=30),
        ),
    ]
