# Generated by Django 4.2 on 2023-09-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0007_alter_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awards',
            name='best_coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='best_coach', to='khelxa.player'),
        ),
    ]
