# Generated by Django 4.2.3 on 2023-09-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0009_alter_newsandannouncement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='standing',
            name='rank',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
