# Generated by Django 4.0.2 on 2023-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khelxa', '0010_standing_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standing',
            options={'ordering': ['rank']},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='images',
            field=models.ManyToManyField(to='khelxa.Images'),
        ),
        migrations.AlterField(
            model_name='newsandannouncement',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='news_and_announcements', to='khelxa.Images'),
        ),
    ]
