from django.urls import path
from .views import *

urlpatterns = [
    path('standings/', StandingListCreateView.as_view(), name='standing-list-create'),
    path('standings/<int:pk>/', StandingDetailView.as_view(), name='standing-detail'),
    path('season/',SeasonView.as_view(),name='season'),
    path('fixtures/', FixtureListView.as_view(), name='fixture-list'),
    path('top-scorer/<int:season_id>/', TopScorerTeamView.as_view(), name='top-scorer'),
    path('total-goals/<int:season_id>/', TotalGoalsView.as_view(), name='total-goals'),
    path('fastest-goal/<int:season_id>/', FastestGoalByPlayerView.as_view(), name='fastest-goal'),
    path('top-results/<int:season_id>/', TopResultsView.as_view(), name='top-results'),
    path('top-card-teams/<int:season_id>/', TopCardTeamsView.as_view(), name='top-card-teams'),
    path('top-scorer-player/<int:season_id>/', TopScorerByPlayerView.as_view(), name='top-scorer-player'),
    path('total-cards/<int:season_id>/', TotalCardsView.as_view(), name='total-cards'),
    path('awards/',CreateGetAwards.as_view(),name='awards'),
    path('sponsers/',CreateGetSponsersView.as_view(),name='sponsers'),
    path('update_awards/<int:id>/',UpdateAwardsView.as_view(),name='update_awards'),
    path('update_sponsers/<int:id>/',UpdateSponsersView.as_view(),name='update_sponsers'),
    path('contactus/',CreateGetContactUsView.as_view(),name='contactus'),
    path('contactus/<int:id>/',UpdateContactUsView.as_view(),name='update_awards'),
    path('video/',VideoView.as_view(),name='video'),
    path('video/<int:id>/',UpdateVideoView.as_view(),name='video'),
    path('gallery/create_with_images/', GalleryCreateWithImagesView.as_view(), name='gallery-create-with-images'),
    path('gallery/', GalleryListView.as_view(), name='gallery-list'),
    path('gallery/<int:pk>/', GalleryDetailView.as_view(), name='gallery-detail'),
    path('gallery/update/<int:pk>/', GalleryUpdateView.as_view(), name='gallery-update'),
    path('gallery/delete/<int:pk>/', GalleryDeleteView.as_view(), name='gallery-delete'),
    path('clubs/',CreateGetClubView.as_view(),name='clubs'),
    path('clubs/<int:id>/',UpdateClubView.as_view(),name='clubs'),
    path('player/',CreateGetPlayerView.as_view(),name='player'),
    path('player/<int:id>/',UpdatePlayerView.as_view(),name='player'),
    path('news-announcements/', NewsAndAnnouncementListCreateView.as_view(), name='news-announcements-list-create'),
    path('news-announcements/<int:pk>/', UpdateNewsAndAnnouncementView.as_view(), name='news-announcements-update'),
    path('latest_club/',LatestClubListView.as_view(),name='latest_club'),
    path('testing/',CreateInstanceView.as_view(),name='testing')
    
]
'''
	path("contactus/", ContactView.as_view(), name='contactus'),
	path("fixtures/", FixturesView.as_view(), name='fixtures'),
	path("fixtures/<int:id>/", FixtureRUD.as_view(), name='fixtureupdate'),
	path("awards/", AwardView.as_view(), name='awards'),
	path("awards/<int:id>/", AwardRUD.as_view(), name='awardsupdate'),
	path("club/", ClubView.as_view(), name='club'),
	path("club/<int:id>/", ClubRUD.as_view(), name='clubupdate'),
	path("clubextra/", ClubExtraView.as_view(), name='clubextra'),
	path("clubextra/<int:id>/", ClubExtraRUD.as_view(), name='clubextraupdate'),
	path("gallery/", GalleryView.as_view(), name='gallery'),
	path("gallery/<int:id>/", GalleryRUD.as_view(), name='galleryupdate'),
	path("galleryimage/", GalleryImageView.as_view(), name='galleryimage'),
	path("galleryimage/<int:id>/", GalleryImageRUD.as_view(), name='galleryimageupdate'),
	path("newsandannounce/<int:id>/", NewsandAnnounceView.as_view(), name='newsandannounceupdate'),
	path("newsandannounce/", NewsandAnnounceAPIView.as_view(), name='newsandannounce'),
	path("tournament/", TournamentView.as_view(), name='tournament'),
	path("tournament/<int:id>/", TournamentRUD.as_view(), name='tournamentupdate'),
    '''